### ISSUE TITLE
https URL is redirecting to http

### ISSUE THREAD

**Issue by casschin** [vigetlabs/redirector#18]
I noticed that when I set up a redirect using the redirector gem that a source URL prefixed with `https` will redirect to the destination URL prefixed with `http`. I noticed this after I migrated to this gem from the define redirects in my Rails routes file.

Is there a way to make it redirect to `https`?

**Comment by efatsi** [comment]
Hi @casschin, I don't believe there's anything in this gem that would change the protocol of the request from `https` to `http`. Is it possible that the attributes within the Redirect Rule are specifying a target route at `http`?

**Comment by casschin** [comment]
You're right, I made a mistake when I was testing. It's nothing to do with redirector, my apologies!

**Comment by mantenie** [comment]
I've the same problem.

**Comment by efatsi** [comment]
This has been resolved and pushed to version 1.1.1.

Thanks for the feedback and submissions here.
