### ISSUE TITLE
Add ability to filter by HTTP verbs

### ISSUE THREAD

**Issue by jeffmagill** [vigetlabs/redirector#50]
We have a route
```
resources :widgets
```
It produces the routes:
```
widgets GET      /widgets(.:format)             widgets#index
widgets POST     /widgets(.:format)             widgets#create
 widget PATCH    /widgets/:id(.:format)         widgets#update
        PUT      /widgets/:id(.:format)         widgets#update
        DELETE   /widgets/:id(.:format)         widgets#destroy
```
We want to redirect `GET /widgets`, but we want to keep `POST /widgets` and the others. Since the redirect rules do not consider HTTP verbs, we are faced with the problem of either, 
1. Not redirecting `/widgets`, or,
2. Losing all the other endpoints

If there was an **HTTP Verb** column+filter, then we could micromanage this better.

**Comment by efatsi** [comment]
Hey there. We don't have a lot of the expertise on staff anymore that developed this gem, but can you do this with a RequestEnvironmentRule? Quoting the README

> Redirect rules can also have further Rack/HTTP environment (mainly HTTP headers) conditions via RequestEnvironmentRules. These define a key in the rack environment passed into the middleware and a value match you require for the redirect rule it's tied too. Similar to the redirect rules these RequestEnvironmentRules can be string matches or regex matches. A redirect rule can have as many of these environment rules as you need.

Might you be able to isolate the HTTP verb in the headers, and match on that?

**Comment by efatsi** [comment]
If so, it would be awesome if you could write up something we could add to the README so others in the future don't run into the same problme.
